"""Methodology V2.2: freeze the CV-selected FD001 model (YAML-driven, clean fit).

Training protocol (V2_2_REPAIR_PLAN.md V2.2-1, V2.2-13):

    1. READ every configurable value from configs/final_model_v2_2_fd001.yaml
       (no duplicate constants - the YAML is the source of truth).
    2. Calibration engine IDs NEVER enter training: no validation_data, no
       early stopping, no epoch selection, no preprocessing fitting.
    3. Fit preprocessing on the 85 development engines only.
    4. Train for exactly fixed_epoch_count epochs (development-only rule),
       with NO validation_data and NO control callbacks.
    5. Save model + scaler + metadata. NO official evaluation here: post-hoc
       metrics are generated by scripts/run_v2_2_posthoc.py AFTER conformal
       calibration (scripts/run_v2_2_conformal.py).

Artifacts:
    models/v2_2/fd001_<candidate>.keras
    models/v2_2/fd001_scaler.joblib
    experiments/v2_2/fd001_final_fit_metadata.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from joblib import dump as dump_joblib
from sklearn.preprocessing import StandardScaler

from rul_prediction.benchmark.v2 import ROOT
from rul_prediction.benchmark.v2_2 import git_provenance
from rul_prediction.data.canonical_hash import canonical_sha256_json
from rul_prediction.data.loader import SENSOR_COLUMNS, load_train
from rul_prediction.data.preprocessing import transform
from rul_prediction.data.v2_preprocessing import add_raw_rul, build_v2_train_sequences
from rul_prediction.training.trainer import set_seed


def final_fit_plan(cfg: dict, frame: pd.DataFrame) -> dict:
    """Resolve the clean final-fit plan; asserts the V2.2 calibration-isolation invariant.

    Returns the resolved plan (train IDs, calibration IDs, epochs, window, ...).
    This function is the single source of truth tested by Test A.
    """
    assert cfg["methodology_version"] == "2.2" and cfg["dataset"] == "FD001"
    splits = cfg["splits"]
    manifest = json.loads(Path(splits["development_engine_manifest"]).read_text(encoding="utf-8"))
    dev_ids = set(manifest["development_engine_ids"])
    cal_ids = set(manifest["calibration_engine_ids"])
    assert len(dev_ids) == 85 and len(cal_ids) == 15
    assert dev_ids.isdisjoint(cal_ids)

    # canonical hash verification (platform-independent)
    assert manifest["development_engine_ids_sha256"] == canonical_sha256_json(sorted(dev_ids))
    assert manifest["calibration_engine_ids_sha256"] == canonical_sha256_json(sorted(cal_ids))
    assert set(frame["engine_id"].unique()) == dev_ids | cal_ids

    control = cfg["training_control"]
    assert control["validation_data"] == "NONE in final fit (calibration + outer-eval engines untouched)"
    model_cfg = cfg["model"]
    epochs = control.get("fixed_epoch_count")
    n_estimators = control.get("fixed_n_estimators")
    assert (epochs is None) != (n_estimators is None), "exactly one duration mechanism"
    if model_cfg["architecture"] == "xgboost":
        assert int(n_estimators) == int(model_cfg["n_estimators"]), (
            "training_control.fixed_n_estimators must match model.n_estimators")
        return {
            "dev_ids": dev_ids, "cal_ids": cal_ids, "window": int(model_cfg["window"]),
            "candidate": model_cfg["candidate_name"], "architecture": model_cfg["architecture"],
            "n_estimators": int(n_estimators),
            "max_depth": int(model_cfg["max_depth"]),
            "learning_rate": float(model_cfg["learning_rate"]),
            "subsample": float(model_cfg["subsample"]),
            "colsample_bytree": float(model_cfg["colsample_bytree"]),
            "seed": int(model_cfg.get("random_state", model_cfg.get("seed"))),
            "early_stopping_rounds": model_cfg.get("early_stopping_rounds"),
        }
    return {
        "dev_ids": dev_ids, "cal_ids": cal_ids, "window": int(model_cfg["window"]),
        "epochs": int(epochs) if epochs else None,
        "n_estimators": None,
        "seed": int(model_cfg["seed"]), "loss": model_cfg["loss"],
        "batch_size": int(model_cfg["batch_size"]),
        "learning_rate": float(model_cfg["learning_rate"]),
        "candidate": model_cfg["candidate_name"], "architecture": model_cfg["architecture"],
    }


def fit_final_model(plan: dict, frame: pd.DataFrame, data_dir: str | Path):
    """Fit preprocessing + model on the 85 development engines ONLY, fixed duration, NO validation."""
    from rul_prediction.benchmark.v2 import classical_features
    from rul_prediction.models.baseline import random_forest
    from rul_prediction.models.v2_models import v2_gru, v2_lstm
    from rul_prediction.models.xgboost_model import xgboost_regressor

    dev_ids = plan["dev_ids"]
    window = plan["window"]
    scaler = StandardScaler().fit(
        frame[frame["engine_id"].isin(dev_ids)][SENSOR_COLUMNS].to_numpy(dtype=float))
    rows = frame[frame["engine_id"].isin(dev_ids)]
    X, y, ids, n_observed, masks = build_v2_train_sequences(
        transform(rows, SENSOR_COLUMNS, scaler),
        rows["engine_id"].to_numpy(), add_raw_rul(rows)["rul"].to_numpy(dtype=np.float32),
        window)
    F, _ = classical_features(X, ids, n_observed, window)

    start = time.perf_counter()
    arch = plan["architecture"]
    if arch == "rf":
        model = random_forest(plan["seed"]).fit(F, y)
    elif arch == "xgboost":
        model = xgboost_regressor(plan["seed"])
        model.set_params(
            max_depth=plan["max_depth"],
            learning_rate=plan["learning_rate"],
            subsample=plan["subsample"],
            colsample_bytree=plan["colsample_bytree"],
            n_estimators=plan["n_estimators"],
            random_state=plan["seed"],
            early_stopping_rounds=plan["early_stopping_rounds"],
        )
        model.fit(F, y, verbose=False)
    else:
        set_seed(plan["seed"])
        builder = v2_gru if arch == "gru" else v2_lstm
        model = builder(window, X.shape[2], loss=plan["loss"], seed=plan["seed"],
                        learning_rate=plan["learning_rate"])
        model.fit([X, masks], y, batch_size=plan["batch_size"],
                  epochs=plan["epochs"], verbose=0)
    training_time = round(time.perf_counter() - start, 2)
    return model, scaler, training_time


def main() -> None:
    parser = argparse.ArgumentParser(description="Freeze V2.2 FD001 final model")
    parser.add_argument("--config", default="configs/final_model_v2_2_fd001.yaml")
    parser.add_argument("--data-dir", default="data/raw")
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text(encoding="utf-8"))
    frame = load_train("FD001", args.data_dir)
    plan = final_fit_plan(cfg, frame)

    # Hard isolation assertions (Test A invariants, enforced here too)
    assert plan["cal_ids"].isdisjoint(plan["dev_ids"])

    model, scaler, training_time = fit_final_model(plan, frame, args.data_dir)

    out_dir = ROOT / "models" / "v2_2"
    out_dir.mkdir(parents=True, exist_ok=True)
    model_path = out_dir / f"fd001_{plan['candidate']}.keras"
    if plan["architecture"] in ("rf", "xgboost"):
        model_path = out_dir / f"fd001_{plan['candidate']}.joblib"
        dump_joblib(model, model_path)
    else:
        model.save(model_path)
    scaler_path = out_dir / "fd001_scaler.joblib"
    dump_joblib(scaler, scaler_path)
    print(f"saved model {model_path} + scaler ({training_time}s)")

    meta = {
        "methodology_version": "2.2",
        "dataset": "FD001",
        "candidate": plan["candidate"],
        "architecture": plan["architecture"],
        "window": plan["window"],
        "fixed_epoch_count": plan.get("epochs"),
        "fixed_n_estimators": plan.get("n_estimators"),
        "training_engine_count": len(plan["dev_ids"]),
        "calibration_engine_count": len(plan["cal_ids"]),
        "calibration_contact_in_fitting": False,
        "validation_data_in_final_fit": False,
        "training_time": training_time,
        "train_ids_sha256": canonical_sha256_json(sorted(plan["dev_ids"])),
        "cal_ids_sha256": canonical_sha256_json(sorted(plan["cal_ids"])),
        "model_path": str(model_path.relative_to(ROOT)),
        "scaler_path": str(scaler_path.relative_to(ROOT)),
        "provenance": git_provenance(),
    }
    if plan["architecture"] == "xgboost":
        meta["model_params"] = {k: plan[k] for k in (
            "max_depth", "learning_rate", "subsample", "colsample_bytree",
            "n_estimators", "early_stopping_rounds")}
    else:
        meta["model_params"] = {"loss": plan["loss"], "batch_size": plan["batch_size"],
                                "learning_rate": plan["learning_rate"], "seed": plan["seed"]}
    Path("experiments/v2_2/fd001_final_fit_metadata.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8")
    print(json.dumps(meta, indent=2))


if __name__ == "__main__":
    main()